### ISSUE TITLE
Jasmine 3.0.0 breaks Angular 5.2 tests

### ISSUE THREAD

**Issue by rnadler** [angular/zone.js#1015]
Duplicated from: https://github.com/jasmine/jasmine/issues/1496
## Expected Behavior
Tests work with Jasmine 2.9.1

## Current Behavior
With Jasmine 3.0.0, **all** tests fail with this error:
```
TypeError: Cannot read property 'run' of null
  at <Jasmine>
  at UserContext.<anonymous> home/bobn/Projects/app/node_modules/zone.js/dist/jasmine-patch.js:106:1)
  at <Jasmine>
  at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask home/bobn/Projects/app/node_modules/zone.js/dist/zone.js:421:1)
  at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask home/bobn/Projects/app/node_modules/zone.js/dist/zone.js:188:1)
  at drainMicroTaskQueue home/bobn/Projects/app/node_modules/zone.js/dist/zone.js:595:1)
  at <Jasmine>
```
Same behavior using Angular 5.2.3 and 5.2.4.
It seems as though **jasmine-patch.js** is no longer compatible with Jasmine 3.0.0.
## Your Environment

Ubuntu 16.04
Chrome 64.0.3282 (Linux)
package.json: **"zone.js": "^0.8.20"**
`ng -v`
> Angular CLI: 1.6.7
> Node: 8.8.1
> OS: linux x64
> Angular: 5.2.4
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> <nowiki>@</nowiki>angular/cli: 1.6.7
> <nowiki>@</nowiki>angular-devkit/build-optimizer: 0.0.42
> <nowiki>@</nowiki>angular-devkit/core: 0.0.29
> <nowiki>@</nowiki>angular-devkit/schematics: 0.0.52
> <nowiki>@</nowiki>ngtools/json-schema: 1.1.0
> <nowiki>@</nowiki>ngtools/webpack: 1.9.7
> <nowiki>@</nowiki>schematics/angular: 0.1.17
> typescript: 2.7.1
> webpack: 3.10.0

**Comment by pe8ter** [comment]
The variable `testProxyZone` in _jasmine-patch.js_ is unexpectedly `null`.

**Comment by JiaLiPassion** [comment]
I will check it, thank you!

**Comment by JiaLiPassion** [comment]
@rnadler , I have found the reason and will provide a PR soon.

**Comment by dfederm** [comment]
@JiaLiPassion I just tried your changes and they mostly work. My tests which don't use a `done` callback, `fakeasync` or `async` seem to not properly report their status (they run but they don't count as "ran", "failed" or "skipped"). To be fair, I'm not sure if that's a zone.js thing or something with jasmine, karma-jasmine, or the reporter I'm using.

**Comment by JiaLiPassion** [comment]
@dfederm , could you post a reproduce repo? I haven't tried with `angular`, I am still making this PR working in `zone.js` repo.

**Comment by dfederm** [comment]
@JiaLiPassion looks like it's throwing here:
![image](https://user-images.githubusercontent.com/6445614/36015905-61210dcc-0d25-11e8-8f9c-201c4220c825.png)

`Zone.current` is a ProxyZone whose parent is the ambientZone ("<root>").

The repro is actually really simple:
```
    it("should pass", (done) => {
        expect(0).toBe(0);
        done();
    });

    it("should also pass, but doesn't", () => {
        expect(0).toBe(0);
    });
```

PS. I'm not very versed in zone.js, so please excuse any naivete on my part.

**Comment by JiaLiPassion** [comment]
@dfederm , ok , thank you for the debug information, I will check it.

**Comment by dfederm** [comment]
@JiaLiPassion so I started deleting more and more code to help narrow it down and realized I lied a little. My tests actually have a `beforeEach` which does something like...

```
    beforeEach(done => {
        TestBed.configureTestingModule({ ... })
            .compileComponents()
            .then(() => {
                fixture = TestBed.createComponent(...);
            })
            .then(done)
            .catch(done.fail);
    });
```

If I remove that, it seems to work. So it seems like something goes awry if I do something angular-ish and async in the `beforeEach` but then the test is fully synchronous.

Also, this doesn't solve the problem, but in jasmine-patch.js if I replace
```
throw new Error('Unexpected Zone: ' + Zone.current.name);
```
with
```
this.fail(new Error('Unexpected Zone: ' + Zone.current.name));
```

I get a real failure instead of the test being excluded silently.

**Comment by dfederm** [comment]
@JiaLiPassion I just tried your latest changes that handles child zones and my tests now pass! Assuming that's the "right" fix and not a temp hack you were just playing with.

**Comment by JiaLiPassion** [comment]
@dfederm , thank you for quick confirm, yes, check `child zone` is the right fix, I will do some other test to make sure it work with `async` and `fakeAsync`.

**Comment by proustibat** [comment]
Don't know if it can help but I have the same issue with the version 3.0.0: 
`TypeError: null is not an object (evaluating 'testProxyZone.run') `

All logs are visible on the pull request that tries to update Jasmine here: 
https://travis-ci.org/proustibat/fbrgsmn.mobile.app/builds/338193121

Indeed I also have a beforeEach with async in my tests

**Comment by JiaLiPassion** [comment]
@proustibat , the `null` issue have been fixed, I will do more test, thank you.

**Comment by dfederm** [comment]
@JiaLiPassion I'm not meaning to badger you but was wondering what the status was on a fix and if you had an ETA for getting this merged in and package pushed. I only ask so I can evaluate whether it's worth it for me to push a private package with your pending fix just for myself to use temporarily, or whether I should just wait for an official fix. Thanks again for your hard work on this issue!

**Comment by JiaLiPassion** [comment]
@dfederm , sure, you can use this temp branch for test now, just update your `package.json`,

```
"zone.js": "git://github.com/JiaLiPassion/zone.js#jasmine-dist"
```

you can test with current status of PR. I will still need to test this PR for little more, please use this branch for now.

**Comment by andreimcristof** [comment]
why is this closed, please? 
I have the exact same error and zone.js is updated to the latest version shown in its package.json: 0.8.20
is the isssue still requiring further work?
thank you

**Comment by JiaLiPassion** [comment]
@andreimcristof , this issue have been fixed, but not released.  you can use 
`"zone.js": "git://github.com/JiaLiPassion/zone.js#jasmine-dist"`
in your `package.json` for now and wait for the next release.

**Comment by gezn** [comment]
@JiaLiPassion  I moved to the branch as you suggested and it throws the following exception 

```
TypeError: Cannot read property 'length' of undefined
	    at <Jasmine>
	    at UserContext.<anonymous> (webpack:///src/models/sgtinencoding/epc-utils.spec.ts:324:21 <- karma-test-shim.js:67673:52)
	    at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:388:0 <- karma-test-shim.js:63086:26)
	    at ProxyZoneSpec.onInvoke (webpack:///node_modules/zone.js/dist/proxy.js:79:0 <- karma-test-shim.js:65985:39)
	    at ZoneDelegate.invoke (webpack:///node_modules/zone.js/dist/zone.js:387:0 <- karma-test-shim.js:63085:32)
	    at Zone.run (webpack:///node_modules/zone.js/dist/zone.js:138:0 <- karma-test-shim.js:62836:43)
	    at UserContext.<anonymous> (webpack:///node_modules/zone.js/dist/jasmine-patch.js:96:0 <- karma-test-shim.js:66185:51)
	    at <Jasmine>
	    at ZoneDelegate.invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:0 <- karma-test-shim.js:63119:31)
	    at Zone.runTask (webpack:///node_modules/zone.js/dist/zone.js:188:0 <- karma-test-shim.js:62886:47)
	    at drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone.js:595:0 <- karma-test-shim.js:63293:35)
	    at <Jasmine>

```
that seems similar to this other issue https://github.com/angular/zone.js/issues/399

any ideas?

**Comment by JiaLiPassion** [comment]
@gezn, could you provide a reproduce repo? Thanks.

**Comment by gezn** [comment]
@JiaLiPassion  creating a empty repo to reproduce the issue was unsuccessful dough I believe that should be an version incompatibility with the current project were we are using it. I'm sorry about the inconveniences. downgring karma jasmin and some others solved it.

**Comment by jimmymain** [comment]
JiaLiPassion, I was successfully using `git://github.com/JiaLiPassion/zone.js#jasmine-dist` for a while, I have since updated packages, and now I am getting a new undefined variable `Zone`

![image](https://user-images.githubusercontent.com/2555050/36962293-969ae8c0-2057-11e8-966d-f253dc1360c5.png)

What version of jasmine should we be using until this is fixed?
What other packages need to be downgraded in order for a simple angular test to work?

**Comment by JiaLiPassion** [comment]
@jimmymain , it seems you didn't load `zone.js` itself correctly.
Until the fix is released, you should use 

- jasmine 2.8 (I have tested 2.4.1, 2.8, 2.9.x)
- no other libraries are needed.

**Comment by Koslun** [comment]
@JiaLiPassion @jimmymain `2.99.1` is also working for me, might it just be that I'm not using a specific method combination?

**Comment by jimmymain** [comment]
@koslun thanks, using 2.9.0 - seems o.k.

**Comment by rbirkgit** [comment]
Why is this close? I just tried with jasmine-core 3.1.0 and still get the same error:

TypeError: Cannot read property 'run' of null

**Comment by tarundhillon** [comment]
I am using the below combination where neither 2.9.0 or 2.8.0 are working 

`"dependencies": {
    "@angular/animations": "^5.2.7",
    "@angular/common": "^5.2.7",
    "@angular/compiler": "^5.2.7",
    "@angular/core": "^5.2.7",
    "@angular/forms": "^5.2.7",
    "@angular/http": "^5.2.7",
    "@angular/platform-browser": "^5.2.7",
    "@angular/platform-browser-dynamic": "^5.2.7",
    "@angular/router": "^5.2.7",
    "@webcomponents/custom-elements": "^1.0.8",
    "angular2-jwt": "^0.2.3",
    "clarity-angular": "^0.10.27",
    "clarity-icons": "^0.10.27",
    "clarity-ui": "^0.10.27",
    "core-js": "^2.5.3",
    "d3-dsv": "^1.0.8",
    "gulp": "^3.9.1",
    "gulp-awspublish": "^3.3.1",
    "gulp-cloudfront-invalidate": "^0.1.5",
    "gulp-rename": "^1.2.2",
    "jasmine": "2.8.0",
    "jwt-decode": "^2.2.0",
    "node-sass": "^4.7.2",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.7.2",
    "@angular/compiler-cli": "^5.2.7",
    "@angular/language-service": "^5.2.7",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^9.4.6",
    "amazon-cognito-identity-js": "^2.0.1",
    "aws-sdk": "^2.205.0",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.2",
    "karma-htmlfile-reporter": "^0.3.5",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-spec-reporter": "0.0.32",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }`

**Comment by JiaLiPassion** [comment]
@rbirkgit ,@andreimcristof , this issue have been fixed, but not released. you can use
"zone.js": "git://github.com/JiaLiPassion/zone.js#jasmine-dist"
in your package.json for now and wait for the next release.

**Comment by JiaLiPassion** [comment]
@tarundhillon , could you post a reproduce repo? or could you try to update your package.json to "zone.js": "git://github.com/JiaLiPassion/zone.js#jasmine-dist"?

**Comment by rbirkgit** [comment]
I don't understand why it's closed if it's not released? Maybe that normal github practice. What should I be looking for to know if it's released?

**Comment by JiaLiPassion** [comment]
@rbirkgit , thanks for the suggestion, current process is , when bug is fixed, the issue itself will be closed, but you can only get the bug fix when the new version was released to `npm`. I believe most open source project does the same thing.

**Comment by rickvandermeij-aanzee** [comment]
@JiaLiPassion That is not entirely true. the bug(hotfix) is fixed, when the release will be on master branch and has an version tag. Your master pipeline will release an `npm` version corresponding to the `package.json`.

**Comment by JiaLiPassion** [comment]
@rickvandermeij-aanzee , current `zone.js` will not automatically update the `dist` folder until it has a new `version tag`, so even the bugfix is merged to master, you still have to wait for the new version.

**Comment by tarundhillon** [comment]
@JiaLiPassion Thanks .. "zone.js": "git://github.com/JiaLiPassion/zone.js#jasmine-dist" worked. Looking forward to the next release.

**Comment by TriplicateGirl** [comment]
@JiaLiPassion Is there a reason why this hasn't been released yet? It seems this was fixed 23 days ago, just curious why it wasn't pushed out

**Comment by JiaLiPassion** [comment]
@TriplicateGirl , I am not sure when the next version will release,  please wait a little longer.

**Comment by danger89** [comment]
Waiting for the new release w000t :+1:

**Comment by Boriszn** [comment]
Is it fixed ? B/c I'm using latest version of Jasmine(3.1.0) and Zone(0.8.20) still same issue. Or should I use  some specific version ("zone.js": "git://github.com/JiaLiPassion/zone.js#jasmine-dist") ? 

Could please help me (This issue blocks my work a bit :((( )

**Comment by emartinez-usgs** [comment]
Is it possible you could create a tag on your repository that includes this fix? This would greatly help systems running NPM but that do not have a Git client installed. Tags create .tgz archives that can be directly installed with a URL reference (HTTP) and do not require Git.

Is there another way to access an archive of a specific branch?

**Comment by JiaLiPassion** [comment]
@emartinez-usgs , I have created a tag here https://github.com/JiaLiPassion/zone.js/releases
@Boriszn, the bug has been fixed but not released, so please use the version in your `package.json`.

```
"zone.js": "git://github.com/JiaLiPassion/zone.js#jasmine-dist"
```

**Comment by emartinez-usgs** [comment]
@JiaLiPassion Thanks. That worked for us and helped out a lot.

**Comment by alexzaytsev-newsroomly** [comment]
Can this maybe not be closed until this fix is released?

**Comment by JiaLiPassion** [comment]
@corvinrok , @alexzaytsev-newsroomly , please wait for the next release. you can use 
```
"zone.js": "git://github.com/JiaLiPassion/zone.js#jasmine-dist"
```
for test now.

**Comment by matiger** [comment]
When is the next release going to be?

**Comment by qnlzgl** [comment]
Thanks very much @JiaLiPassion , the fix works perfectly for me.

**Comment by richadr** [comment]
For the people watching this issue, the fix appears to have been released so you can remove the hack in your package.json.

https://github.com/angular/zone.js/blob/master/CHANGELOG.md#0821-2018-03-30
(see the jasmine bullet)

**Comment by roinou** [comment]
I can confirm: `"zone.js": "^0.8.26"` and `"jasmine-core": "~3.1.0"` work together

**Comment by ssunny2** [comment]
A few test cases are still failing after using the above versions. Before upgrading zone.js and jasmine-core, all specs used to pass. Most of the failing ones have 'toBe' and 'toEqual' assertions. It seems the specs are not being tested in order, for example in a describe block with 3 'It' functions, the third(or the second, I found it to be inconsistent) 'It' is being tested first thereby assigning a value to a variable 
 which is used in the first 'It' function. This breaks the spec for the first 'It' with assertions like toEqual  and toBe, where LHS must be equal RHS. Anybody else facing the same issues?

**Comment by ssunny2** [comment]
@JiaLiPassion Thanks for the clarification. I do understand why it's not recommended,but could you please tell me where I can configure the specs to run in order.

**Comment by JiaLiPassion** [comment]
@ssunny2 , sure, you can find it here, https://jasmine.github.io/setup/nodejs.html
Search `random`, you can set `random: false`.

**Comment by ssunny2** [comment]
I looked up the file, and found that random is already set to false

`{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
`

on running the test by appending --random:false also didn't yield the expected result. Some specs are still failing.

**Comment by JiaLiPassion** [comment]
I am not sure which part is wrong, you can try to downgrade to `jasmine 2.x`, but still use latest `zone.js` to see what happened, if it worked, maybe your test code have some other conflict with `jasmine 3.x`. Or you can post your reproduce repo here, I can help to find the reason.

**Comment by ssunny2** [comment]
OK I'll try the steps you suggested, although I'm sure its the TCs that are having conficts with jasmine 3.x. I can't post the repo here though, it isn't my personal project. Thanks for the help.

**Comment by denisbeklarov** [comment]
Found a way to disable random mode by jasmine for angular (6 in my case). Put this in karma.conf.js:
```
module.exports = function (config) {
    config.set({
       // your configuration
        client: {
            jasmine: {
                random: false
            }
        }
}))
```

**Comment by chetankh23** [comment]
I am facing the same issue. I upgraded from Angular 5.2 to Angular 6 and my all the unit tests are breaking apart randomly. I even tried setting up the random mode by jasmine as per @denisbeklarov comment. But its still failing. I tried to use the 
`"zone.js": "git://github.com/JiaLiPassion/zone.js#jasmine-dist"`
in my package.json. But it's still failing.
