### ISSUE TITLE
'Uncaught TypeError: Cannot set property stack of [object Object] which has only a getter' with Angular

### ISSUE THREAD

**Issue by matthewsorenson-tr** [angular/zone.js#427]
Hi, I observed this error when migrating to Angular RC6 with zone.js 0.6.17. 
Error:
>long-stack-trace-zone.js:135
>Uncaught TypeError: Cannot set property stack of [object Object] which has only a getter
>onHandleError	@	long-stack-trace-zone.js:135
>ZoneDelegate.handleError	@	zone.js:336
>onHandleError	@	ng_zone_impl.js:60
>ZoneDelegate.handleError	@	zone.js:336
>Zone.runTask	@	zone.js:268
>ZoneTask.invoke	@	zone.js:433

I see that the error caught on zone.js:267 is a ViewWrappedError (which has a proto chain of WrappedError -> BaseError -> Error -> Object). On long-stack-trace-zone.js:123, descriptor ends up as null, which leads to long-stack-trace-zone.js:135, where error.stack cannot be set since WrappedError used Object.defineProperty and didn't define a setter.

Is this an issue with Angular or Zone.js?

Note: This error went away after I fixed the issue that was causing the exception to be thrown in the first place, but it still seems like incorrect error handling.

**Comment by dancancro** [comment]
What did you do to fix the issue? Here's my stack trace with zone 0.6.27 and Angular 2.0.0-rc.6 ...

```
Uncaught TypeError: Cannot set property stack of [object Object] which has only a getter
onHandleError @ long-stack-trace-zone.js?fcc3:135
ZoneDelegate.handleError @ zone.js?fad3:327
onHandleError @ VM22016:61
ZoneDelegate.handleError @ zone.js?fad3:327
Zone.runGuarded @ zone.js?fad3:233
NgZoneImpl.runInnerGuarded @ VM22016:74
NgZone.runGuarded @ VM21996:239
outsideHandler @ VM22196:30
ZoneDelegate.invokeTask @ zone.js?fad3:356
Zone.runTask @ zone.js?fad3:256
ZoneTask.invoke @ zone.js?fad3:423
```

**Comment by matthewsorenson-tr** [comment]
I set a breakpoint on line 135 in long-stack-trace-zone.js, triggered this issue, then went to the console and ran `renderLongStackTrace(parentTask.data && parentTask.data[creationTrace], error.stack)` to get the stack trace that should have been displayed. In my case, it was a warning from the dev mode change detection code stating that a value had changed during the change detection process and a new cycle wasn't triggered. This was fixed by moving code in some components from ngAfterViewInit() to ngAfterContentInit().

**Comment by tmakin** [comment]
I've run into this issue too over the last couple of days following RC 6 upgrade with zone.js 0.6.17. A range of different errors seem to trigger it. For example, a simple undefined variable error inside a component function call. I was able to see the true error using a breakpoint on long-stack-trace-zone.js:135 as suggested above.

**Comment by dancancro** [comment]
@matthewsorenson-tr Thank you very much. That gave me a familiar error. I was wondering what happened to it. Welcome back, old converting circular structure to json error.

**Comment by ocombe** [comment]
I've been having this error a lot on various problems, the error message doesn't help at all, it's really hard to debug it :(

**Comment by ocombe** [comment]
@mhevery I really wish we could have the stack trace when this error happens instead of this cryptic message
It's probably a bug in one of the last zone.js versions that prevents the console.error to be shown

**Comment by retrospectacus** [comment]
You can temporarily work around this by changing line 135 in node_modules/zone.js/dist/long-stack-trace-zone.js
to Object.defineProperty(error, 'stack', renderLongStackTrace(parentTask.data && parentTask.data[creationTrace], error.stack));

**Comment by smith64fx** [comment]
@matthewsorenson-tr yeah man, you made my day :D thanks

**Comment by timblakely** [comment]
I believe this was fixed in #425

**Comment by ocombe** [comment]
nice ! now we just have to wait for a new release :)

**Comment by TheSaturn** [comment]
Please fix bug. I don't what is wrong with my app due to this bug

**Comment by matthewsorenson-tr** [comment]
Looks like #425 was included in 0.6.21, so I think this issue can be closed.

**Comment by tobiaseisenschenk** [comment]
I Still get this EXCEPTION: Cannot set property stack of [object Object] which has only a getter
I am on "zone.js": "^0.7.2"
above solution doesn't really do it for me, therefore it is hard to debug.

**Comment by JiaLiPassion** [comment]
@matthewsorenson-tr , could you provide a reproduce repo or plunker or a full error stack trace, thank you.

**Comment by Yonet** [comment]
@JiaLiPassion I am having the same error. Here is the my stack:

"Error: Uncaught (in promise): TypeError: Cannot set property stack of [object Object] which has only a getter
TypeError: Cannot set property stack of [object Object] which has only a getter
    at assignAll (http://localhost:4200/vendor.bundle.js:119266:29)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:6624:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:6686:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:64015:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:92435:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:92408:18)
    at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:64961:20)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:75458:42)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:26352:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:26319:26)
    at http://localhost:4200/vendor.bundle.js:26255:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:26255:29)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:26325:22)
    at http://localhost:4200/vendor.bundle.js:26255:58
    at resolvePromise (http://localhost:4200/vendor.bundle.js:119063:31) [angular]
    at resolvePromise (http://localhost:4200/vendor.bundle.js:119048:17) [angular]
    at http://localhost:4200/vendor.bundle.js:119097:17 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:32882:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:118836:40) [angular]
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:118713:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:118995:35) [<root>]"

Thanks!

**Comment by JiaLiPassion** [comment]
@Yonet,  Thank you, it is the same with #425, I'll fix it now.

**Comment by jrood** [comment]
For what it's worth, I'm getting the same error. In my case it seems tied to using [this](http://stackoverflow.com/a/35451821/3390298) solution to integrate Material Design Lite with Angular 2.

**Comment by tobiaseisenschenk** [comment]
Here my full stacktrace:
![screen shot 2017-01-13 at 3 05 30 pm](https://cloud.githubusercontent.com/assets/17195795/21945630/e4e0b292-d9a1-11e6-8ffc-f38ab56c1289.png)

**Comment by fcoury** [comment]
@tobiaseisenschenk this happened to me because I had zone.js with `^0.7.2` and 0.7.5 was installed. Pinning it at 0.7.2 worked for us.

**Comment by tobiaseisenschenk** [comment]
great thank you!
I just changed the version in my package.json from ^0.7.5 to 0.7.2 and now the real error is correctly displayed.

**Comment by JiaLiPassion** [comment]
Sorry, the zone.js 0.7.5 have conflict with angular/compiler BaseError, so please use 0.7.4 for now, I have made a new PR to fix this.

**Comment by redplane** [comment]
I changed back to zone 0.7.4, error still occurs.

`zone.js:420 Unhandled Promise rejection: Cannot set property stack of [object Object] which has only a getter ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot set property stack of [object Object] which has only a getter(…) TypeError: Cannot set property stack of [object Object] which has only a getter
    at assignAll (http://localhost:3000/node_modules/zone.js/dist/zone.js:704:29)
    at ViewWrappedError.ZoneAwareError (http://localhost:3000/node_modules/zone.js/dist/zone.js:775:16)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:1174:20)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:1232:20)
    at new ViewWrappedError (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:6552:20)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12760:27)
    at CompiledTemplate.proxyViewClass.DebugAppView.create (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12660:22)
    at CompiledTemplate.proxyViewClass.View_CategoryManagementComponent0.createInternal (/MainApplicationModule/CategoryManagementComponent/component.ngfactory.js:856:19)
    at CompiledTemplate.proxyViewClass.AppView.create (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12253:25)
    at CompiledTemplate.proxyViewClass.DebugAppView.create (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12657:48)
    at CompiledTemplate.proxyViewClass.View_CategoryManagementComponent_Host0.createInternal (/MainApplicationModule/CategoryManagementComponent/host.ngfactory.js:29:19)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12266:25)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12674:56)
    at ComponentFactory.create (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:7690:29)
    at ViewContainerRef_.createComponent (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:9549:66)`


Can anyone help plz .

**Comment by redplane** [comment]
@retrospectacus , I changed the code as you said, but still [object Object]

**Comment by JiaLiPassion** [comment]
@redplane, the assignAll is only intro into zone.js from 0.7.5, can you check your node_modules/zone.js/package.json to check the version?

**Comment by redplane** [comment]
@JiaLiPassion , I've down grade to 0.7.4

**Comment by JiaLiPassion** [comment]
@redplane, ok, maybe the npm release version is not correct, please wait for a while about the new release.

**Comment by redplane** [comment]
@JiaLiPassion , what should I do now ?

**Comment by JiaLiPassion** [comment]
@redplane, if 0.7.4 is not work for you, you can try 0.7.2, it should work, or you can use the attached version, it is based on my new PR.
[zone.js.zip](https://github.com/angular/zone.js/files/706451/zone.js.zip)

**Comment by redplane** [comment]
@JiaLiPassion , ok I'll give it a shot and tell you about the result later. Thank you for your support :)

**Comment by tsm91** [comment]
I also noticed for some weird reason `npm i` will still install the `0.7.5` version having `zone.js": "0.7.2"` in package.json. But doing `npm i --save zone.js@0.7.2` works.

**Comment by nmtoan07** [comment]
I have the same issue too.
After downgrade to 0.7.2, it works!

**Comment by grapgrap** [comment]
I have same issue too. But, I could ran same code at last friday.

**Comment by LasTanzen** [comment]
I was able to fix it with downgrading from 0.7.5 to 0.7.4. Thanks

**Comment by kibbled** [comment]
Zone.js seems very fragile at times, can we put more tests into place to make sure that minor revisions don't break important features? I wasted hours on this, it was returning bogus exception.

**Comment by xtianjohns** [comment]
@JiaLiPassion is your PR for this #601?

**Comment by JiaLiPassion** [comment]
@kibbled, yes , you are right, I will add more test cases from angular/angular to make sure zone.js will not break major features, sorry for the inconvenience.

**Comment by JiaLiPassion** [comment]
@xtianjohns , yes, my PR will fix this one, and #595,#601,#603

**Comment by kibbled** [comment]
@JiaLiPassion no problem, let me know if you guys need help testing the fix

**Comment by sunpasup** [comment]
i am still getting this below error 
 

i have zone.js@0.7.5 and zone @0.3.4

here is the full stack    helppp 

EXCEPTION: Cannot set property stack of [object Object] which has only a getter
ErrorHandler.handleError @ core.umd.js:3472
(anonymous) @ core.umd.js:8347
ZoneDelegate.invoke @ zone.js:242
onInvoke @ core.umd.js:4391
ZoneDelegate.invoke @ zone.js:241
Zone.run @ zone.js:113
(anonymous) @ zone.js:535
ZoneDelegate.invokeTask @ zone.js:275
onInvokeTask @ core.umd.js:4382
ZoneDelegate.invokeTask @ zone.js:274
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:433
ZoneTask.invoke @ zone.js:349
<img width="1438" alt="screen shot 2017-01-17 at 2 04 48 pm" src="https://cloud.githubusercontent.com/assets/24596204/22041993/0bcfdd3c-dcbe-11e6-90ad-defd0b26c132.png">

**Comment by kibbled** [comment]
@sunpasup revert back to zone.js@0.7.2 - I don't think the fix will be in until 0.7.6 at the earliest.

**Comment by sunpasup** [comment]
Thanks Kibbled its worked.

**Comment by JiaLiPassion** [comment]
zone.js 0.7.6 has been released, please try it.

**Comment by longsleep** [comment]
0.7.6 now shows useful information in Error in :0:0 caused by: .... :+1:

**Comment by Dzixxx** [comment]
In my case, problem was releated with unsubscribing Subscribtion which was not subscribed, maybe it'll help someone to find his problem :)

**Comment by redplane** [comment]
I've tried with zone 0.7.4, it worked . Thank all of you :)
