### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by marius-oprea** [angular/zone.js#746]
- Create a new empty project with @angular/cli 1.0.0
- Update the packages in the package.json to the latest versions ( "zone.js": "^0.8.8" and "@angular/core": "^4.0.3")
- npm install and npm start
- check your browser console (I used Chrome)
![untitled](https://cloud.githubusercontent.com/assets/1609131/25299885/ff08f81a-270c-11e7-835f-f94d63ca51a8.png)

**Comment by JiaLiPassion** [comment]
I will check it now

**Comment by cooniur** [comment]
I'm curious about if this bug would have any side effects on Angular 4.0?

**Comment by irowbin** [comment]
Same here while upgrading v0.8.5 to 0.8.8
![capture](https://cloud.githubusercontent.com/assets/13050078/25312503/b2cbba4e-283a-11e7-8217-d6d7ca48630f.PNG)

**Comment by JiaLiPassion** [comment]
@irowbin , it has been fixed in #747

**Comment by JohannesHoppe** [comment]
Quickfix:

```
// package.json

  "dependencies": {
    "zone.js": "0.8.5"
  },
```
and afterwards: `npm i`
Cheers!

**Comment by txwizard** [comment]
This is to confirm that I, an outside user (outside the development team, that is), has confirmed that upgrading to version 0.8.9 resolved that issue. My browser of choice is Google Chrome, Version 58.0.3029.81 (64-bit), running on Windows 7 Professional, SP 1, fully patched.

**Comment by dfanica** [comment]
I've tried all `node.js` versions and I'm still getting a similar error.
I'm now on the latest `0.8.11`, and everything else is pretty much the latest version.

```
ERROR TypeError: Cannot read property 'apply' of undefined
    at Up (ima3.js:687)
    at Sp.L (ima3.js:688)
    at Ig (ima3.js:470)
    at R (ima3.js:468)
    at Ep.B (ima3.js:678)
    at Fg (ima3.js:465)
    at Bg (ima3.js:466)
    at ima3.js:464
    at ZoneDelegate.invokeTask (zone.js:424)
    at Object.onInvokeTask (core.es5.js:4140)
```

Anyone has any ideas?

**Comment by JiaLiPassion** [comment]
Can you provide a reproduce sample?
